#!/usr/bin/env bash

set -e

echo "Setting up dev environment..."
# Source bash libraries
for library in "$(dirname "$0")"/libraries/*; do
. "${library}"
done

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Linux/brew dependencies
installer::get::dependencies

# Install brew
brew::install
brew::export::path

# Install apps & packages with Brewfile
ulimit -n 8192 # Increase file descriptors limit to solve brew installing awscli
brew::install::packages

#### Shell (zsh) configuration ####
# Install Oh My Zsh
zsh::get::omz

# Install Powerlevel10k zsh theme
zsh::get::p10k

#Install kubetail
installer::get::kubetail

# Install additional zsh plugins not included with Oh My Zsh
zsh::get::plugin zsh-autosuggestions zsh-syntax-highlighting

# Link custom .zsh files to Oh My Zsh custom folder
dotfiles::link::custom_zsh

# Link ssh config
dotfiles::link::ssh_config

# Link $HOME dotfiles
dotfiles::link::files

# Create this file to suppress error from z on first 'cd'
touch $HOME/.z

# Set default shell depending on MacOS or Linux
system::set::default_shell

# Install asdf version manager plugins
asdf::install::plugins

dotfiles::complete
