#!/usr/bin/env bash

set -e

echo "Setting up dev environment..."
# Source bash libraries
for library in "$(dirname "$0")"/custom/libraries/*; do
. "${library}"
done

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install brew
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing Homebrew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null
else
  echo "Homebrew already installed, updating..."
  brew update
fi
# Install apps & packages with Brewfile
echo "Installing packages and apps with Homebrew & Cask..."
brew bundle --file=dependencies/Brewfile --no-lock --no-upgrade
if [[ $(uname) == "Darwin" ]]; then
  brew bundle --file=dependencies/Brewfile.cask --no-lock --no-upgrade
fi

#### Shell (zsh) configuration ####
# Install Oh My Zsh
zsh::get::omz

# Install Powerlevel10k zsh theme
zsh::get::p10k

#Install kubetail
installer::get::kubetail

# Install additional zsh plugins not included with Oh My Zsh
zsh::get::plugin zsh-autosuggestions zsh-syntax-highlighting

# Link custom .zsh files to Oh My Zsh custom folder
dotfiles::link::custom_zsh

# Link ssh config
dotfiles::link::ssh_config

# Link $HOME dotfiles
dotfiles::link::files

# Create this file to suppress error from z on first 'cd'
touch $HOME/.z

# Set default shell depending on MacOS or Linux
system::set::default_shell

# Install asdf version manager plugins
asdf::install::plugins

echo "Setup complete, quit terminal and open iTerm to continue..."
