brew cask install "atom"
apm install Sublime-Style-Column-Selection
apm install atom-beautify
apm install atom-formatter-jsbeautify
apm install busy-signal
apm install change-case
apm install editorconfig
apm install file-icons@
apm install go-debug
apm install go-plus
apm install intentions
apm install language-docker
apm install language-haml
apm install language-javascript-jsx
apm install linter
apm install linter-docker
apm install linter-flake8
apm install linter-ui-default
apm install prettier-atom
apm install sort-lines
apm install split-diff
