#!/usr/bin/env zsh

# ===  Make it sexy ===
source "$HOME/.shell_style"

# === Plugins ===
source "$HOME/.zsh_plugins.sh"

# === Secrets ===
source "$HOME/.shell/.work_secrets"
source "$HOME/.shell/.personal_secrets"

# === Shell exports and functions ===
source "$HOME/.shell/.exports"
source "$HOME/.shell/.aliases"
source "$HOME/.shell/.functions"
source "$HOME/.shell/.k8rc"
source "$HOME/.shell/.extra"
