# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"

# SETUP PATHS
declare -a dirs_to_prepend
dirs_to_prepend=(
  "$HOME/bin"
  "/usr/local/sbin"
  "/usr/local/git/bin"
  "/usr/local/"
  "/usr/local/opt/libpq/bin"
  "/usr/local/opt/mysql-client/bin"
  "/usr/local/opt/openssl/bin"
)

# Explicitly configured $PATH
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

for dir in ${(k)dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dir}:$PATH"
  fi
done

unset dirs_to_prepend

export PATH

# Set completion options
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="false"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Oh-my-zsh plugins.
# Be cautious, too many and your terminal will be very slow
plugins=(
  bundler
  docker
  docker-compose
  dotenv
  git
  history-substring-search
  kubectl
  osx
  tig
  yarn
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh_reload
)

source $ZSH/oh-my-zsh.sh

# Source me up
source $HOME/.shell_env

# Make less the default pager, add some options and enable syntax highlight using source-highlight
LESSPIPE=`which src-hilite-lesspipe.sh`
[ -n "$LESSPIPE" ] && export LESSOPEN="| ${LESSPIPE} %s"
less_options=(
  # If the entire text fits on one screen, just show it and quit. (Be more
  # like "cat" and less like "more".)
  --quit-if-one-screen
  # Do not clear the screen first.
  --no-init
  # Like "smartcase" in Vim: ignore case unless the search pattern is mixed.
  --ignore-case
  # Do not automatically wrap long lines.
  --chop-long-lines
  # Allow ANSI colour escapes, but no other escapes.
  --RAW-CONTROL-CHARS
  # Do not ring the bell when trying to scroll past the end of the buffer.
  --quiet
  # Do not complain when we are on a dumb terminal.
  --dumb
);
export LESS="${less_options[*]}"
export PAGER='less'

if [[ -f ~/.shell/.user ]]; then
  source ~/.shell/.user
fi
source $HOME/.shell_post
